tsj\memsBundle\Entity\Item:
    type: entity
    table: item
    id:
        id:
          type: integer
          generator: { strategy: AUTO }
    fields:
        title:
          type: string
          length: 255
        description:
          type: text
        link:
          type: string
          length: 255
        item_type:
          type: string
          lenght: 11
        item_status:
          type: integer
        created_at:
          type: datetime
        updated_at:
          type: datetime
          nullable: true
        created_by:
          type: integer
        updated_by:
          type: integer
          nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreateValues ]
        preUpdate: [ setUpdateValues ]