#       Security z logowaniem z fosuserbundle
security:
            encoders:
                FOS\UserBundle\Model\UserInterface: sha512

            role_hierarchy:
                ROLE_ADMIN:       ROLE_USER
                ROLE_SUPER_ADMIN: ROLE_ADMIN

            providers:
                fos_userbundle:
                            id: fos_user.user_provider.username_email

            firewalls:
                secured_area:
                            pattern: ^/
                            anonymous: true
                            form_login:
                                provider: fos_userbundle
                                csrf_provider: form.csrf_provider
                            oauth:
                                resource_owners:
                                    facebook:           /login/check-facebook
                                login_path:        /login
                                use_forward:       false
                                failure_path:      /login

                                oauth_user_provider:
                                    service: tsjmems.user_provider
                            logout: true



            access_control:
                - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/admin/, role: ROLE_ADMIN }

                - { path: ^/favourites, role: ROLE_USER }
